/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.polijic.jpql.gui;

import helpers.validador;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo
 */
public class usuario extends javax.swing.JFrame {

    /*
     * Creates new form usuario
     */
    
    public String avatar; 
    
    
    public usuario() {
        initComponents(); 
        cboChange.setVisible(false);
        avatar = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvatar = new javax.swing.JLabel();
        lblCambiar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSeudonimo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPuntaje = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        cboChange = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAvatar.setBackground(new java.awt.Color(204, 204, 204));
        lblAvatar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Default.png")));
        lblAvatar.setToolTipText("");
        lblAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCambiar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCambiar.setText("[ cambiar ] ");
        lblCambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblCambiarMouseReleased(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCambiarMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("Seudonimo");

        txtSeudonimo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtSeudonimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeudonimoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("Puntaje");

        txtPuntaje.setEditable(false);
        txtPuntaje.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtPuntaje.setEnabled(false);
        txtPuntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuntajeActionPerformed(evt);
            }
        });
        txtPuntaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPuntajeKeyTyped(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        cboChange.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Default", "Putty", "Cinforosa", "Oscar" }));
        cboChange.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboChangeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCambiar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(77, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPuntaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(txtSeudonimo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSeudonimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblCambiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSeudonimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeudonimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeudonimoActionPerformed

    private void txtPuntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuntajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuntajeActionPerformed

    private void txtPuntajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuntajeKeyTyped
        // TODO add your handling code here:
        validador val = new validador(false);
        val.numerico(evt);
        
    }//GEN-LAST:event_txtPuntajeKeyTyped

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        
        String seudonimo  = txtSeudonimo.getText();
        String puntaje    = txtPuntaje.getText();
        
        if( seudonimo.equals("") || puntaje.equals("") )
        {
             JOptionPane.showMessageDialog(this, " campos incompletos.", "Alerta",2);
        }
        else
        {
            
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void lblCambiarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambiarMouseReleased
        // TODO add your handling code here:
        cboChange.setVisible(true);
        lblCambiar.setVisible(false);
    }//GEN-LAST:event_lblCambiarMouseReleased

    private void lblCambiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambiarMousePressed
        // TODO add your handling code here:
     //           cboChange.setVisible(false);
      //  lblCambiar.setVisible(true);
    }//GEN-LAST:event_lblCambiarMousePressed

    private void cboChangeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboChangeItemStateChanged
        // TODO add your handling code here:
        
        avatar = cboChange.getSelectedItem().toString();
        
        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/"+avatar+".png"))); // NOI18N
        
    }//GEN-LAST:event_cboChangeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox cboChange;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblCambiar;
    private javax.swing.JTextField txtPuntaje;
    private javax.swing.JTextField txtSeudonimo;
    // End of variables declaration//GEN-END:variables
}
